### ISSUE TITLE
documentation is not up to date

### ISSUE THREAD

**Issue by hbt** [sebastianbergmann/phpunit-skeleton-generator#41]
documentation (current) https://phpunit.de/manual/current/en/skeleton-generator.html  uses version 1.0.0 where as current repository is at 2.0.1

README does not have usage either.

Please update the doc when you get a chance.

Thank you

**Comment by sebastianbergmann** [comment]
It's intentionally missing from the PHPUnit documentation as the usage of this tool is no longer encouraged.
